name: ditonton
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  about:
    path: packages/about
  core:
    path: packages/core
  movie:
    path: packages/movie
  tv:
    path: packages/tv

  cupertino_icons: ^1.0.2
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  get_it: ^7.7.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  bloc_test: ^9.1.7
  build_runner: ^2.0.4
  mockito: ^5.4.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/