name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  about:
    path: ../about
  movie:
    path: ../movie
  tv:
    path: ../tv

  cached_network_image: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.2
  firebase_crashlytics: ^4.0.4
  flutter_bloc: ^8.1.3
  google_fonts: ^6.2.1
  http: ^1.1.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.0.4
  mockito: ^5.4.3
  sqflite_common_ffi: ^2.3.3
  test: any

flutter: